language: node_js

node_js:
  - "0.10"

notifications:
  irc:
    channels:
      - "irc.mozilla.org#apps"
    on_success: never
    on_failure: always
    use_notice: true
  email: false

install:
  - ./travis_install.sh

script:
  - nodeunit $(pwd)/tests/tests.js
